; ------------------------------------------------------------------------------
; Symbols extracted from
; build/.obj/source/sound/pcm/command.o
; build/.obj/source/sound/pcm/data_r1.o
; build/.obj/source/sound/pcm/data_r3.o
; build/.obj/source/sound/pcm/data_r4.o
; build/.obj/source/sound/pcm/data_r5.o
; build/.obj/source/sound/pcm/data_r6.o
; build/.obj/source/sound/pcm/data_r7.o
; build/.obj/source/sound/pcm/data_r8.o
; build/.obj/source/sound/pcm/data_boss.o
; build/.obj/source/sound/pcm/data_final.o
; ------------------------------------------------------------------------------

PCM_SONG_START          equ $81
PCM_SONG_PAST           equ $81
PCM_SONG_END            equ $8F
PCM_SFX_START           equ $B0
PCM_SFX_UNKOWN          equ $B0
PCM_SFX_FUTURE          equ $B1
PCM_SFX_PAST            equ $B2
PCM_SFX_ALRIGHT         equ $B3
PCM_SFX_OUTTA_HERE      equ $B4
PCM_SFX_YES             equ $B5
PCM_SFX_YEAH            equ $B6
PCM_SFX_AMY_GIGGLE      equ $B7
PCM_SFX_AMY_YELP        equ $B8
PCM_SFX_STOMP           equ $B9
PCM_SFX_BUMPER          equ $BA
PCM_SFX_SHATTER         equ $BB
PCM_SFX_END             equ $BF
PCM_CMD_FADE_OUT        equ $E0
PCM_CMD_START           equ $E0
PCM_CMD_STOP            equ $E1
PCM_CMD_PAUSE           equ $E2
PCM_CMD_UNPAUSE         equ $E3
PCM_CMD_MUTE            equ $E4
PCM_CMD_END             equ $E4

; ------------------------------------------------------------------------------
