; ------------------------------------------------------------------------------
; Symbols extracted from
; build/.obj/source/sound/pcm/main.o
; build/.obj/pcm.sym
; ------------------------------------------------------------------------------

pcm.sound_queue equ $A
PcmDriver       equ $40000
RunPcmDriver    equ $40010
PcmDriverOrigin equ $40010
InitPcmDriver   equ $40014
PcmVariables    equ $40018

; ------------------------------------------------------------------------------
